# Generated by Django 4.0.3 on 2022-07-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durations',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='durations',
            name='stop',
            field=models.DateTimeField(),
        ),
    ]
